apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel9-deployment
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-nginx
          image: crcontainerdev.azurecr.io/laravel-nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
        - name: laravel-app
          image: crcontainerdev.azurecr.io/laravel-app
          port
volumes:
  - name: secrets-store01-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-kvname-podid"
