apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel9-deployment
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel
          image: laravelsail/php81-composer
          ports:
            - containerPort: 80
